{% set version = "2.1.1" %}

package:
  name: pendulum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pendulum/pendulum-{{ version }}.tar.gz
  sha256: d97739a7a5d5fc64e98bab46b292ac9f15aee88b5d3851cd6037d011a7b18af0

build:
  number: 0
  script:
    - rm -f pyproject.toml  # [not win]
    - del /f pyproject.toml  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - python-dateutil >=2.8.1,<3.0
    - pytzdata >=2020.1
    - typing >=3.6,<4.0  # [py<35]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pendulum

about:
  home: https://pendulum.eustace.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python datetimes made easy
  description: |
    Drop-in replacement for the standard datetime class.
    It behaves exactly like it but with many improvements.
  doc_url: https://pendulum.eustace.io/docs/
  dev_url: https://github.com/sdispater/pendulum

extra:
  recipe-maintainers:
    - mcs07
    - ocefpaf
    - xylar
