{% set version = "2.0.4" %}

package:
  name: pendulum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pendulum/pendulum-{{ version }}.tar.gz
  sha256: cf535d36c063575d4752af36df928882b2e0e31541b4482c97d63752785f9fcb
  patches:
    - no-pyproject_toml.patch

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - python-dateutil >=2.6,<3.0
    - pytzdata >=2018.3
    - typing >=3.6,<4.0  # [py<35]

test:
  imports:
    - pendulum

about:
  home: https://pendulum.eustace.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python datetimes made easy'
  description: |
    Drop-in replacement for the standard datetime class.
    It behaves exactly like it but with many improvements.
  doc_url: https://pendulum.eustace.io/docs/
  dev_url: https://github.com/sdispater/pendulum

extra:
  recipe-maintainers:
    - mcs07
    - ocefpaf
