{% set version = "1.3.1" %}

package:
  name: pendulum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pendulum/pendulum-{{ version }}.tar.gz
  sha256: f24e475e41cdbd43834e14652830cc0192d006ef0e8633b13c0e126d9a391d2f

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - python-dateutil
    - pytzdata >=2017.2.2
    - tzlocal

test:
  imports:
    - pendulum
  commands:
    - conda inspect linkages -p $PREFIX pendulum  # [not win]
    - conda inspect objects -p $PREFIX pendulum  # [osx]

about:
  home: https://pendulum.eustace.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python datetimes made easy'
  description: |
    Drop-in replacement for the standard datetime class.
    It behaves exactly like it but with many improvements.
  doc_url: https://pendulum.eustace.io/docs/
  dev_url: https://github.com/sdispater/pendulum

extra:
  recipe-maintainers:
    - mcs07
    - ocefpaf
