{% set version = "3.0.0" %}

package:
  name: pendulum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pendulum/pendulum-{{ version }}.tar.gz
  sha256: 5d034998dea404ec31fae27af6b22cff1708f830a1ed7353be4d1019bb9f584e
  patches:
    # https://github.com/conda-forge/pendulum-feedstock/commit/34b57a4e8a83577a1d7e25460444683aa3128071
    - patches/0001-remove-tzdata-dep-for-pip-check.patch

build:
  number: 0
  skip: True  # [py<38]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  build:
    - {{ compiler('rust') }}
    - patch        # [not win]
    - m2-patch    # [win]
  host:
    - python
    - pip
    # - poetry-core
    - maturin >=1.0,<2.0
  run:
    - python
    - python-dateutil >=2.6
    - tzdata >=2020.1
    - backports.zoneinfo >=0.2.1  # [py<39]
    - time-machine >=2.6.0
    - importlib-resources >=5.9.0  # [py<39]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pendulum

about:
  home: https://pendulum.eustace.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python datetimes made easy
  description: |
    Drop-in replacement for the standard datetime class.
    It behaves exactly like it but with many improvements.
  doc_url: https://pendulum.eustace.io/docs/
  dev_url: https://github.com/sdispater/pendulum

extra:
  recipe-maintainers:
    - mcs07
    - ocefpaf
    - xylar
