{% set version = "3.1.0" %}

package:
  name: pendulum
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pendulum/pendulum-{{ version }}.tar.gz
  sha256: 66f96303560f41d097bee7d2dc98ffca716fbb3a832c4b3062034c2d45865015

build:
  number: 1
  skip: true  # [py<39]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
    - setuptools
    - wheel
  run:
    - python
    - python-dateutil >=2.6
    - python-tzdata >=2020.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pendulum

about:
  home: https://pendulum.eustace.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python datetimes made easy
  description: |
    Drop-in replacement for the standard datetime class.
    It behaves exactly like it but with many improvements.
  doc_url: https://pendulum.eustace.io/docs/
  dev_url: https://github.com/sdispater/pendulum

extra:
  recipe-maintainers:
    - mcs07
    - ocefpaf
    - xylar
