# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TH7yeglbwuaFaPFfXcVETokWoXRje9n+KNy6lL/ten//FVzxnxTNWx0apmHK+Xh3bRA1OHCjFalpFSFjGhL/XlTo/TeHhbLWODkWa4oHkm7YnBUoa31fAPL6fnRnNqz9XAwIC6IWOYT+KADNcJ5ac28y677eg3Yv/AyZqzHboQsx9DMFu5QlPQ6Ktx8OY7e9tfqJKAHwVs4sf9QAhNxx3mz7vrRNSQ0t150qXYx+h64BGe5/+dGusP09ehWFiZvLiYw9XWdlt0Lm0zo+1EDeRLSfy5IZPr2KkXSLwM2OVV94WSZj/+oZ+XbRVGj3C3Dn7L5d32fDUrB5kWkMkbXODebI6I6755i3M8pmUvcV+k/RABTUIRUbX+pi46zGQyLbSiu5cwnxe8dfImcVI7ya0OQOeT3TWiiD0emB8QRyI+5g4oOkBCxa0rVQIuBHFuUTDi5re38lhYn7VueR3BFzDX3y995ZRxDg83zpR90IpCXmBL8nYH/h/AnA+eZZrpBqU1GwHLupDmLv11V6TQtEoCYRZu5iKm+1Rw8CT4gKCJvPtmjDduQu41slJZU5xhLF5Vq7OVzvKA2tuMC6hPC2CwN5O5o1eZi6W0RtFrzRwp+POKOTZZHukCByPgLesdwzbFIIQBUH5qRTrL9KvI3W+CEoUFup/OdztDefVjqWgBY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
