travis:
  secure:
    BINSTAR_TOKEN: kHeSqCDqIbcEcaAKB82kmYUqo3M4yBemggC02kO17x+qP1kZbI2ejvOFUsyfN3hw1d2gKBfcy6mg2xeDoH5eYpTpEt2sm+Mtbm7NQV9uy5ZDTKSiSwiW+pob+jGZ521FpfLz0rrFo4CPR6Elep/zZ1FBpw25itYIdHkXVSlAeCIoFDKOPk5ZEc3/jCANU54beCz8u4HrA1Qgic74UeySlTGpazi3jPiJ7gEOFGEYjTUCGDWWN6gHCW7XzkDqMOD7CD3FS6dnpDxM5XLuT28hyXl15SppYHwzBC9MS6yWTXUsDxMZES1FqZV8v7GTeXtABMy35RiR0Cwdhd0fTAHkA9lpUHIvEOOZbRs0LhzM3o+ilhNId5RE+b2Smu5AIAOSNVv3NI5s5uxZrHJoiJ0WoppugoY6NDACw9z7MZG0yl/DN3BYKoaBNv75xZUaN3w7klvE6Rh88BlsD236KpQJRBiKVVjIP9PwTt2jS2p3CZTnPfUylimfdgsr3wJ7Yziv/UlAcqlZaiSl56tM6D55vjwzQLsNBJzi75Z3XdXwN0ykuYLYsgjr+8JHiizq6Haw5J2Y0j5H/R6huKXWJxs/EURIZTucttRaLtB2B+xTL9H9BB4GvPN4MFmAWXMWhgL0vectg9zgfxaHlUcsSNBT/kay+epC/DySFJMNdWMPzkg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
