travis:
  secure:
    BINSTAR_TOKEN: TH7yeglbwuaFaPFfXcVETokWoXRje9n+KNy6lL/ten//FVzxnxTNWx0apmHK+Xh3bRA1OHCjFalpFSFjGhL/XlTo/TeHhbLWODkWa4oHkm7YnBUoa31fAPL6fnRnNqz9XAwIC6IWOYT+KADNcJ5ac28y677eg3Yv/AyZqzHboQsx9DMFu5QlPQ6Ktx8OY7e9tfqJKAHwVs4sf9QAhNxx3mz7vrRNSQ0t150qXYx+h64BGe5/+dGusP09ehWFiZvLiYw9XWdlt0Lm0zo+1EDeRLSfy5IZPr2KkXSLwM2OVV94WSZj/+oZ+XbRVGj3C3Dn7L5d32fDUrB5kWkMkbXODebI6I6755i3M8pmUvcV+k/RABTUIRUbX+pi46zGQyLbSiu5cwnxe8dfImcVI7ya0OQOeT3TWiiD0emB8QRyI+5g4oOkBCxa0rVQIuBHFuUTDi5re38lhYn7VueR3BFzDX3y995ZRxDg83zpR90IpCXmBL8nYH/h/AnA+eZZrpBqU1GwHLupDmLv11V6TQtEoCYRZu5iKm+1Rw8CT4gKCJvPtmjDduQu41slJZU5xhLF5Vq7OVzvKA2tuMC6hPC2CwN5O5o1eZi6W0RtFrzRwp+POKOTZZHukCByPgLesdwzbFIIQBUH5qRTrL9KvI3W+CEoUFup/OdztDefVjqWgBY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
